TAP_DANCE_ENABLE = yes
TRI_LAYER_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes

VPATH += keyboards/gboards
COMBO_ENABLE = yes

LTO_ENABLE = yes
